# New window
bind -n M-t new-window -c "#{pane_current_path}"

# Split panes
bind -n M-\| split-window -h -c "#{pane_current_path}"
bind -n M--  split-window -v -c "#{pane_current_path}"

# Switch windows
bind -n M-h previous-window
bind -n M-l next-window

# Vim-style pane navigation (no prefix)
bind -n M-H select-pane -L
bind -n M-J select-pane -D
bind -n M-K select-pane -U
bind -n M-L select-pane -R

# Optional: resize panes with Shift+Alt (Meta)
bind -n C-M-H resize-pane -L 5
bind -n C-M-J resize-pane -D 5
bind -n C-M-K resize-pane -U 5
bind -n C-M-L resize-pane -R 5

# Kill current pane
bind -n M-x kill-pane

set -g @catppuccin_flavor 'mocha'

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status 2

set -g status-position top
set -g status-style bg=default

setw -g window-status-format "#[fg=#a6e3a1,bold] #W "
setw -g window-status-current-format "#[fg=#181825,bg=#a6e3a1,bold] #W "

set -g status-left  ""
set -g status-right "#[fg=#181825,bg=#b4befe,bold] %Y-%m-%d %H:%M "

#set -g status-format[1] "#[bg=#1e1e2e]#(printf '%*s' \"$(tmux display -p '#{client_width}')\" '')#[default]"
set -g status-format[1] '#[bg=default]#(printf "%%*s" "#{client_width}" "")#[default]'

